### ISSUE TITLE
Paste emoji grids

### ISSUE THREAD

**Issue by rwmpelstilzchen** [beerriot/dewordle#1]
A suggestion: add an option to paste emoji grids instead of clicking each tile manually.

**Comment by beerriot** [comment]
I like it. I need to figure out a place to put it in the UI, and then learn to match those larger-than-one-byte characters correctly.

The "quick" workaround I've been using is to type out the pattern as the hash at the end of the URL. 2=🟩, 1=🟨, 0=⬜️, just run all the lines together. So If I wanted to paste

🟨🟩🟩🟩⬜
🟩🟨🟩🟨⬜
🟩🟩⬜🟩🟨
🟨🟨🟩⬜🟩

I'll type it out:

12220
21210
22021
11202

Then run it together after a # at the end of the URL. https://dewordle.beerriot.com/#12220212102202111202

Paste is still a much better idea. Just documenting alternatives until I can get to it.

**Comment by beerriot** [comment]
That was fun. Addressed in 17c7f0d5. See what you think. You should be able to paste anything that includes the colored box emojis into the input field at the bottom, and it will work out the patterns. That is, it ignores everything that isn't a color box. Just press enter, or click outside the input field. Thanks for filing the issue!

**Comment by rwmpelstilzchen** [comment]
:-)
